/*
 * Echo Service
 *
 * Echo Service API consists of a single service which returns a message.
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package echo

type ExamplepbNewNestedMessage struct {
	Foo string `json:"foo,omitempty"`
	Bar string `json:"bar,omitempty"`
}
